server:
  port: 8080
spring:
  freemarker:
    suffix: .ftl
    cache: false
  application:
    name: agile-dev
  datasource:
    url: jdbc:h2:file:./data/${application.name}
    username: guoshengkai
    password: guoshengkai

